### ISSUE TITLE
implement OAUTH with gmail

### ISSUE THREAD

**Issue by coded1guy** [GitHub-Campus-Experts-Unilag/DevZenBackend#1]
**Read the README.md file before you begin**

- setup the signup and login functionality in the /auth/services folder
- create the routes in the /auth/routes folder
- add the swagger documentation in the /auth/routes folder

**Comment by Alfred-Emmanuel** [comment]
Hi @coded1guy  could i be assigned this issue also?

**Comment by NureniJamiu** [comment]
Hi @coded1guy , I would like to work on this issue please

**Comment by coded1guy** [comment]
> Hi, I would like to work on this issue please

Cool, I'll assign the issue to you
