### ISSUE TITLE
[Feat]: Implement sharing ability for users on your zenboard & html preview. 

### ISSUE THREAD

**Issue by tdadadavid** [GitHub-Campus-Experts-Unilag/DevZenBackend#12]
Checkout the share page on the figma
Write the documentation

**Comment by Alfred-Emmanuel** [comment]
Could this be assigned to me please?

**Comment by tdadadavid** [comment]
Assigned!
Happy Hacking.

**Comment by Alfred-Emmanuel** [comment]
Thank you

**Comment by tdadadavid** [comment]
@Alfred-Emmanuel, are you actively working on this issue

**Comment by Alfred-Emmanuel** [comment]
Yes I am, this is the same issue we are discussing about on the social
media platform
